In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import KFold

In [2]:
#Part 1 Decision Tree
mnist = pd.read_csv("mnist.csv")
data = np.array(mnist)
print(data)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [5 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]]


In [12]:
#get 1000 instances
sample=[]
train_label = []
for i in range (0, 10):
    count = 0
    for j in range (0,10000):
        if data[j][0] == i and count != 100:
            sample.append(data[j])
            train_label.append(data[j][0])
            count+=1
#1000 instances from origin data
print(len(sample))
sample = np.array(sample)
sample = sample[0:, 1:]
train_label = np.array(train_label)
print(sample.shape)

1000
(1000, 784)


In [13]:
clf = DecisionTreeClassifier()
clf.fit(sample, train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [14]:
#Part 2 Decision Tree
test = data[0:, 1:]
actual_label = data[0: ,0]
print(clf.score(test, actual_label))

0.7047


In [15]:
#Part 1 MLP
mlp = MLPClassifier()
mlp.fit(sample, train_label)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [16]:
#Part 2 MLP
print(mlp.score(test, actual_label))

0.8347


In [42]:
#Part 3
kf = KFold(n_splits=2, shuffle = True)
print(kf)

clf_score = 0
mpl_score = 0
for train_index, test_index in kf.split(sample):
    X_train, X_test = sample[train_index], sample[test_index]
    y_train, y_test = train_label[train_index], train_label[test_index]
    
    clf.fit(X_train, y_train)
    clf_score +=clf.score(X_test, y_test)

    mlp.fit(X_train, y_train)
    mpl_score += mlp.score(X_test, y_test)
print("decision tree score is: ", clf_score/2)
print("MPL score is: ", mpl_score/2)

KFold(n_splits=2, random_state=None, shuffle=True)
decision tree score is:  0.62
MPL score is:  0.767


In [44]:
kf = KFold(n_splits=4, shuffle = True)
print(kf)

clf_score = 0
mpl_score = 0
for train_index, test_index in kf.split(sample):
    X_train, X_test = sample[train_index], sample[test_index]
    y_train, y_test = train_label[train_index], train_label[test_index]
    
    clf.fit(X_train, y_train)
    clf_score +=clf.score(X_test, y_test)

    mlp.fit(X_train, y_train)
    mpl_score += mlp.score(X_test, y_test)
    
print("decision tree score is: ", clf_score/4)
print("MPL score is: ", mpl_score/4)

KFold(n_splits=4, random_state=None, shuffle=True)
decision tree score is:  0.642
MPL score is:  0.772
